apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-test-job
  namespace: spark-jobs
spec:
  type: Python
  mode: cluster
  image: "940507692220.dkr.ecr.ap-south-2.amazonaws.com/de-spark-prod:0e967aaab585"   # <-- updated by GitHub Actions with git-sha tag
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/scripts/test_job.py
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1g"
    serviceAccount: spark-driver-sa
    labels:
      version: 3.5.0
  executor:
    cores: 1
    instances: 2
    memory: "1g"
    labels:
      version: 3.5.0
  sparkConf:
    "spark.kubernetes.container.image.pullPolicy": "Always"